/* Stub implementations for mruby initialization functions
 * These are normally generated by mruby's build system
 */

#include <mruby.h>

/* Initialize mrbgems (mruby standard library gems)
 * Empty stub - no gems are included in this minimal build
 */
void mrb_init_mrbgems(mrb_state *mrb) {
	/* No gems to initialize */
	(void)mrb;
}

/* Initialize mrblib (Ruby standard library code)
 * Empty stub - no mrblib included in this minimal build
 */
void mrb_init_mrblib(mrb_state *mrb) {
	/* No mrblib to initialize */
	(void)mrb;
}
